version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Java 11
  pre_build:
    commands:
      - echo Pre-build stage
  build:
    commands:
      - echo Build started on `date`
      - cd homefood-delivery-app/backend   # ✅ Adjust this if your code is deeper
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - homefood-delivery-app/backend/target/*.war   # ✅ Correct artifact path
