version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Java 11
  pre_build:
    commands:
      - echo Pre-build stage
  build:
    commands:
      - echo Build started on `date`
      - cd backend    # ✅ Move into correct folder inside build phase
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - backend/target/*.war   # ✅ Point to correct artifact path
