version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Java 11
  pre_build:
    commands:
      - echo Pre-build stage
      - cd backend     # ✅ Move into backend folder (where pom.xml is)
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - backend/target/*.war    # ✅ Important if WAR is inside backend/target/
