version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Java 17
  pre_build:
    commands:
      - echo Pre-build stage
  build:
    commands:
      - echo Build started on `date`
      - cd homefood-delivery-app/backend
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - chmod +x homefood-delivery-app/backend/scripts/*.sh
artifacts:
  files:
    - homefood-delivery-app/backend/target/*.jar
    - homefood-delivery-app/backend/appspec.yml
    - homefood-delivery-app/backend/scripts/*
  discard-paths: yes

