version: 0.0
os: linux
files:
  - source: target/homefood-backend-1.0.0.jar
    destination: /opt/tomcat9/webapps/

hooks:
  ApplicationStop:
    - location: scripts/stop_tomcat.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: scripts/start_tomcat.sh
      timeout: 20
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timeout: 15
      runas: root
